### ISSUE TITLE
December 2019 - content update

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [microsoft/MCW-Machine-Learning#10]
This workshop is scheduled for a content update. Please review the current workshop, any open issues, and provide update suggestions for review. Thanks!

**Comment by shirolkar** [comment]
Here are some suggestions for the update. 

- Improve setup instructions to address reported user errors in creating the databricks cluster

- Enhancements to the Model Explainability notebook 
   - Remove the use of the deprecated method explain_model() and replace with ExplanationClient.

- Address Erik Zwiefel original feedback
   In the "Deep Learning with Time Series" notebook, the results are underwhelming. My guess (just based on a quick review) is that Daily_Cycles_Used is essentially a random walk and the prediction that optimizes loss is just the average.
   - To fix this feedback we will have to generate new synthetic data with realistic variations in the Daily_Cycles_Used metric used in this notebook. Tune the model for the new dataset and evaluate the time series predictions. 

Please provide your feedback. Thanks.

Jitendra

**Comment by ciprianjichici** [comment]
Here are some suggestions for the content update:

1. Improve the statistics of the data set to get better results with deep learning models.
2. Update all AML screenshots with ones taken from ml.azure.com
3. Improve setup instructions to address reported user errors in creating and configuring Databricks clusters
4. Update the model explainability notebook - remove the deprecated explain_model() and replace it with ExplanationClient
5. Update the WDS section to reflect all other updates

**Comment by mamjadi** [comment]
The instruction and screenshots are not valid anymore in the Task 1: Create an automated machine learning experiment step 3
