### ISSUE TITLE
SDK version update from 1.0.74 to 1.0.83

### ISSUE THREAD

**Issue by himanshuahlawat31** [microsoft/MCW-Machine-Learning#13]
In **Stream Scoring** notebook **cmd 2** sdk version needs to be changed from 1.0.74 to 1.0.83 as experiment will be using 1.0.83 version and if we run 1.0.74 in notebook it will throw an error
![image](https://user-images.githubusercontent.com/57964598/72439845-b0aa5e00-37cd-11ea-83ca-4062e5bbcdcb.png)

in exercise1 task 1 step 13 , we have to add **Battery_ID** in **group by column**
![image](https://user-images.githubusercontent.com/57964598/72440011-11d23180-37ce-11ea-934a-9d3baa135c13.png) Screenshots need to be updated as this option is not available in **Additional configuration window** this option is available after this window

**Comment by lehmus** [comment]
I am experiencing the SDK issue as well. Databricks notebook gives a warning about the SDK version, not an error. The actual error message is `AttributeError: type object 'TextOrCategoricalDtype' has no attribute 'Categorical'`.

**Comment by timahenning** [comment]
Thank you for reporting this issue.  Please take a moment to review the help and support guidance.  https://microsoftcloudworkshop.com/  

Your specific lab section references and screenshots will help expedite support. We will review your issue soon.

Tim

**Comment by shirolkar** [comment]
@timahenning @himanshuahlawat31 @lehmus 
I was able to reproduce the error reported here. The error happens in that the line: best_run, best_model = automl_run.get_output(). I am working on a fix.
