### ISSUE TITLE
Exercise 2: Understanding the automated ML generated forecast model using model explainability

### ISSUE THREAD

**Issue by jhasanjay** [microsoft/MCW-Machine-Learning#2]
/databricks/python/lib/python3.5/site-packages/azureml/explain/model/dataset/dataset_wrapper.py:177: FutureWarning: in the future, boolean array-likes will be handled as a boolean array index
  categorical_col_names = list(np.array(list(tmp_dataset))[(tmp_dataset.applymap(type) == str).all(0)])
AttributeError: 'SystemException' object has no attribute 'from_exception'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<command-1972057256429128> in <module>()
      1 from azureml.train.automl.automlexplainer import explain_model
      2 
----> 3 shap_values, expected_values, sorted_global_importance_values, sorted_global_importance_names, _ , _ = explain_model(best_model, X_train, X_test, best_run=best_run, y_train=y_train)
      4 
      5 #Overall feature importance

/databricks/python/lib/python3.5/site-packages/azureml/train/automl/automlexplainer.py in explain_model(fitted_model, X_train, X_test, best_run, features, y_train, **kwargs)
    166         message = "[RunId:{}]Explain model function met import error. Error message:{}".format(run_id, e)
    167         logger.warning(message)
--> 168         raise SystemException(message).from_exception(e)

AttributeError: 'SystemException' object has no attribute 'from_exception'

**Comment by DawnmarieDesJardins** [comment]
@shirolkar @timahenning 
Hello gentlemen!  Please review and advise.
Dawnmarie

**Comment by stefanvo78** [comment]
Hello gentlemen, I have the same issue. I have to deliver this workshop to a customer of mine beginning of September. Would be great to have a solution until then. 

Many thanks!
Stefan

**Comment by jhasanjay** [comment]
Any update on this issue?

**Comment by shirolkar** [comment]
@jhasanjay and @stefanvo78 
What I noticed is that the updates to Azure Databricks cluster configuration no longer includes 5.4 ML (Scala 2.11, Spark 2.4.3). It has 5.4 (Scala 2.11, Spark 2.4.3) without the ML. So I tried with 5.5 ML (Scala 2.11, Spark 2.4.3) and the lab worked. Can you please delete your cluster and create a new one with 5.5 ML (Scala 2.11, Spark 2.4.3), install the package azureml-sdk[automl_databricks,explain]. Rest of the instructions are the same. Please let me know if this works for you.

**Comment by stefanvo78** [comment]
@shirolkar I retried with an Azure Databricks Cluster Version 5.5 ML. Now it works. But just removing the cluster and creating a new one didn't work for me. I had to delete all resources and start the workshop from the beginning. So could be, that I made an error the first time (propably forgot to ignore the columns in exercise 1). Nevertheless, thanks for your help!

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved.  Thanks @shirolkar !!
