### ISSUE TITLE
AutoMLRun in the Databricks notebook generates error

### ISSUE THREAD

**Issue by mamjadi** [microsoft/MCW-Machine-Learning#21]
In the notebook "Scoring streaming data", when I run cell 13's automl_run = AutoMLRun(existing_experiment, run_id) I get following error:
---------------------------------------------------------------------------
ErrorResponseException                    Traceback (most recent call last)
/local_disk0/pythonVirtualEnvDirs/virtualEnv-920d03a1-cd34-4e96-8a87-639440323338/lib/python3.7/site-packages/azureml/_restclient/workspace_client.py in _execute_with_arguments(self, func, args_list, *args, **kwargs)
     86             else:
---> 87                 return self._call_api(func, *args_list, **kwargs)
     88         except ErrorResponseException as e:

/local_disk0/pythonVirtualEnvDirs/virtualEnv-920d03a1-cd34-4e96-8a87-639440323338/lib/python3.7/site-packages/azureml/_restclient/clientbase.py in _call_api(self, func, *args, **kwargs)
    225             else:
--> 226                 return self._execute_with_base_arguments(func, *args, **kwargs)
    227 

/local_disk0/pythonVirtualEnvDirs/virtualEnv-920d03a1-cd34-4e96-8a87-639440323338/lib/python3.7/site-packages/azureml/_restclient/clientbase.py in _execute_with_base_arguments(self, func, *args, **kwargs)
    278         return ClientBase._execute_func_internal(
--> 279             back_off, total_retry, self._logger, func, _noop_reset, *args, **kwargs)
    280

**Comment by shirolkar** [comment]
@mamjadi @timahenning @DawnmarieDesJardins 
The Scoring streaming data notebook is getting revamped in the March 2020 update. This issue will not be relevant since we will not be loading the AutoML run from the run ID in the new update. FYI. Thanks.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as complete with merge of PR #23
