### ISSUE TITLE
Training data is saved as xls instead of csv

### ISSUE THREAD

**Issue by kristianjaeger** [microsoft/MCW-Machine-Learning#22]
FYI, the Training data is saved as xls instead of csv when one chooses save link as with the step below:
https://github.com/microsoft/MCW-Machine-Learning/blob/master/Hands-on%20lab/Before%20the%20HOL%20-%20Machine%20Learning.md#task-6-download-training-data-to-your-local-machine

Cheers.

**Comment by timahenning** [comment]
Hi @kristianjaeger,

Can you provide more information regarding the problem?

Thanks,

Tim

**Comment by kristianjaeger** [comment]
Thanks, @timahenning . I essentially was following the instructions with Chrome on Windows 10.  In Chrome I used the 'save link as' context menu to save the daily-battery-time-series-v2.csv file. However, it was downloaded in the .xls format.  If I manually changed the extension then it worked with the exercise. Cheers.

**Comment by shirolkar** [comment]
@kristianjaeger @timahenning 
In the March 2020 update to the MCW, we will directly load the training data from the URL when we register the dataset with the Azure Machine Learning workspace. Thus, we will remove the step to download the file to your local computer.

**Comment by kristianjaeger** [comment]
Thanks! Cheers.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as complete with merge of PR #23
