### ISSUE TITLE
cannot import name 'get_db_profile_from_uri' from 'mlflow.utils.uri'

### ISSUE THREAD

**Issue by himanshuahlawat31** [microsoft/MCW-Machine-Learning#25]
while running cmd 25 in exercise 4 , we are getting error as cannot import name 'get_db_profile_from_uri' from 'mlflow.utils.uri'
![image](https://user-images.githubusercontent.com/57964598/88440114-a2976300-ce2a-11ea-89d3-f9e12a383972.png)

**Comment by himanshuahlawat31** [comment]
can you please prioritize this we have lab scheduled for 28th july

**Comment by himanshuahlawat31** [comment]
And now commands in first notebooks are also failing , our databricks version is same as defined in pre-requisites 
![image](https://user-images.githubusercontent.com/57964598/88458827-568e0200-ceae-11ea-8c22-4771e7f0c4e5.png)
![image](https://user-images.githubusercontent.com/57964598/88458834-660d4b00-ceae-11ea-9855-850f26d52c6d.png)

**Comment by shirolkar** [comment]
@himanshuahlawat31 @timahenning 
Please use Databricks Runtime Version: Runtime: 6.5 (Scala 2.11, Spark 2.4.5)
The one you are using is ML version - its different. Let me know if you still have issues after making the change. Thanks.

**Comment by himanshuahlawat31** [comment]
sure, i'll check and will keep you updated

**Comment by himanshuahlawat31** [comment]
tested it is working thanks
