### ISSUE TITLE
stream scoring notebook

### ISSUE THREAD

**Issue by himanshuahlawat31** [microsoft/MCW-Machine-Learning#26]
While running cmd 23 in the notebook i am getting this error
![image](https://user-images.githubusercontent.com/57964598/90604123-00488080-e21a-11ea-9ed3-56982e21ed19.png)

**Comment by shirolkar** [comment]
@himanshuahlawat31 @timahenning  this issue is fixed. Please make sure you register the dataset again from https://databricksdemostore.blob.core.windows.net/data/connected-car/daily-battery-time-series-v2.csv in Exercise 1/Step4.

**Comment by himanshuahlawat31** [comment]
@shirolkar while creating Automated ml run , i created dataset . i didn't understand what was the root cause of issue

**Comment by shirolkar** [comment]
@himanshuahlawat31 I have updated the dataset. So you need to delete or unregister the one your created and recreate again from the same link.

**Comment by himanshuahlawat31** [comment]
okay thanks for the update

**Comment by shirolkar** [comment]
@himanshuahlawat31 Once you create the dataset, you can run the notebook. You do not have to complete Exercise 1.

**Comment by timahenning** [comment]
This issue has been resolved.
