### ISSUE TITLE
screenshot need to be updated

### ISSUE THREAD

**Issue by himanshuahlawat31** [microsoft/MCW-Machine-Learning#27]
In exercise 1 task 1 step 12 , screenshot and instructions need to be updated as Group by column is now replaced with Time series identifier 
![image](https://user-images.githubusercontent.com/57964598/90728473-93e58400-e2e2-11ea-80d5-c3f105c09892.png)

**Comment by timahenning** [comment]
This screenshot will be updated in the coming update in October.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #33
