### ISSUE TITLE
September 2020 Updates

### ISSUE THREAD

**Issue by timahenning** [microsoft/MCW-Machine-Learning#28]

**Comment by shirolkar** [comment]
1. Update all the affected UIs in Azure ML studio.
2. Update to use Databricks Runtime 7.0.
3. Improve the statistics of the dataset to get better results with time series model.
4. Select or generate a new dataset to demonstrate model interpretability and model fairness.
5. Add a new notebook to demonstrate model interpretability and model fairness.
6. Update the WDS section to reflect all the changes.
