### ISSUE TITLE
Stream Scoring notebook error 

### ISSUE THREAD

**Issue by himanshuahlawat31** [microsoft/MCW-Machine-Learning#29]
In cmd 14 when we run the cell , we are getting error as 
![image](https://user-images.githubusercontent.com/57964598/96261318-ed65e880-0fdd-11eb-8a7b-2ea501ab38da.png)
Can you please take a look into this

**Comment by himanshuahlawat31** [comment]
Hi , can you please take a look into this . we have lab scheduled for 26 october

**Comment by akn9050** [comment]
@DawnmarieDesJardins we have lab request on 26th, it will be good if we can fix it before that.

**Comment by DawnmarieDesJardins** [comment]
@timahenning 
Hi Tim, do you have an ETA for a fix on this?  See above presentation date.

**Comment by timahenning** [comment]
@akn9050 We are looking at today.

Tim

**Comment by himanshuahlawat31** [comment]
In exercise 3, while running the cell Create and Run Experiment in the Stream Scoring notebook, I am getting the following error.

![image](https://user-images.githubusercontent.com/57964598/97200152-da6dc800-17d6-11eb-89e4-b1633a03b724.png)

**Comment by shirolkar** [comment]
@himanshuahlawat31  What is the databricks runtime version of your cluster? Thanks. Jitendra

**Comment by himanshuahlawat31** [comment]
HI @shirolkar we have used 6.6 version of cluster

**Comment by shirolkar** [comment]
@himanshuahlawat31  Thanks. Working on a fix.

**Comment by shirolkar** [comment]
@DawnmarieDesJardins I sent a new PR to address this issue. Thanks. @timahenning
