### ISSUE TITLE
Exercise 1 : Creating a forecast model using automated machine learning

### ISSUE THREAD

**Issue by fasalzaman** [microsoft/MCW-Machine-Learning#3]
In Exercixe 1 > task 3 , Once we click on Deploy Best Model, it is directly giving the tab to deploy the Model not just to Register Model. Azure portal UI got updated, Can you please make the required changes as soon as possible in the guide as well ?
Because we have scheduled a Machine Learning workshop on 23rd August,2019.

**Comment by fasalzaman** [comment]
Instead of registering Model, We have to download the Model to our local disk and create a new model named "Battery-Cycles" using the downloaded image. This fix help me out to complete the lab end to end.

**Comment by fasalzaman** [comment]
Can you address these issues and update the repo as soon as possible ?
 We have scheduled a Machine Learning workshop on 23rd August,2019.

**Comment by timahenning** [comment]
Thanks for letting us know.  We will investigate.

Tim

**Comment by fasalzaman** [comment]
please update the lab as soon as possible.
we can't miss the scheduled lab.

regards
Fasal Zaman

**Comment by DawnmarieDesJardins** [comment]
Closing with recent PR.
