### ISSUE TITLE
Facing issue in Stream Scoring Notebook

### ISSUE THREAD

**Issue by anushabc** [microsoft/MCW-Machine-Learning#31]
In exercise 3, while running the cell **Create and Run Experiment** in the Stream Scoring notebook, I am getting the following error.

![ml-error](https://user-images.githubusercontent.com/66515706/97143063-f433ee80-1787-11eb-99d7-545c29e218c3.png)

**Comment by shirolkar** [comment]
@anushabc @timahenning 
PR: https://github.com/microsoft/MCW-Machine-Learning/pull/32#event-3922101767
Should fix this issue. Thanks.
Jitendra

**Comment by shirolkar** [comment]
@timahenning 

This issue is fixed with the latest merge. Thanks.

Jitendra

**Comment by SanjaJo** [comment]
I'm facing the same issue - were there any updates after closing the ticket? Which version of the packages should be installed?

**Comment by DawnmarieDesJardins** [comment]
Reopened for review

**Comment by shirolkar** [comment]
@SanjaJo @DawnmarieDesJardins @timahenning 
Hi SanaJo: You need to use Databricks Runtime Version: Runtime: 6.6 (Scala 2.11, Spark 2.4.5) and install azureml-sdk[automl] on the cluster. The setup instructions were updated at: https://github.com/microsoft/MCW-Machine-Learning/blob/master/Hands-on%20lab/Before%20the%20HOL%20-%20Machine%20Learning.md
You also need the latest code from the repo: https://github.com/microsoft/MCW-Machine-Learning/tree/master/Hands-on%20lab/notebooks
Please let me know if this does not work. If you have issues can you please share logs/error details. Thanks. Jitendra

**Comment by SanjaJo** [comment]
@shirolkar 
Hi Shirolkar, I created another cluster with the same instructions  Runtime: 6.6 (Scala 2.11, Spark 2.4.5) and azureml-sdk[automl] on the cluster. The setup instructions should be the same as the current in the repo. Attached please find the logs
[ADB-logs20201109.txt](https://github.com/microsoft/MCW-Machine-Learning/files/5513120/ADB-logs20201109.txt). azureml.core.VERSION is 1.17.0 if that helps. 
![adb-screenshot](https://user-images.githubusercontent.com/25228870/98592778-7bc64500-22d2-11eb-9d12-9f2f1aefef0c.PNG). Let me know if you need additional information and thanks for the support!

**Comment by shirolkar** [comment]
@SanjaJo The fix is in my brach https://github.com/shirolkar/MCW-Machine-Learning. Please see the cluster and library requirements in https://github.com/shirolkar/MCW-Machine-Learning/blob/master/Hands-on%20lab/Before%20the%20HOL%20-%20Machine%20Learning.md. You will also need the new notebooks from: https://github.com/shirolkar/MCW-Machine-Learning/tree/master/Hands-on%20lab/notebooks. Thanks. Jitendra

**Comment by SanjaJo** [comment]
Hi @shirolkar, that worked thanks a lot!

**Comment by DawnmarieDesJardins** [comment]
Closing as resolved with merge of PR #34
