### ISSUE TITLE
the name of workspace is 'ws' not 'workspace' in notebook of Data Preparation

### ISSUE THREAD

**Issue by i-love-doufunao** [microsoft/MCW-Machine-Learning#35]
![image](https://user-images.githubusercontent.com/42244960/102003440-69f91700-3d42-11eb-84a9-bb8dab0fb37f.png)

**Comment by shirolkar** [comment]
@timahenning I will work on this today. Thanks.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as complete with merge of PR #36
