### ISSUE TITLE
Issue in 4.0 Deep Learning with Text, cmd-4

### ISSUE THREAD

**Issue by Divyasri199** [microsoft/MCW-Machine-Learning#42]
While running the cmd-4 we are getting an error as module 'keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'.

![image](https://user-images.githubusercontent.com/83349577/122379153-3793d500-cf84-11eb-972d-65890bc5b1df.png)
Can you please take a look into this.

**Comment by akn9050** [comment]
Hi @DawnmarieDesJardins  @timahenning we have an event schedued for 24th and 25th of June. Is is possible to priorities the fixing of the issue before that.

**Comment by timahenning** [comment]
@akn9050 We will try.

Tim

**Comment by shirolkar** [comment]
@timahenning @akn9050  I have fixed this issue and submitted a PR. Thanks. Jitendra

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #43
