### ISSUE TITLE
5.0 Model Interpretability failing 

### ISSUE THREAD

**Issue by himanshuahlawat31** [microsoft/MCW-Machine-Learning#44]
HI , while running the cmd 21 we are getting the error :

![image](https://user-images.githubusercontent.com/57964598/122832532-1d058700-d309-11eb-8e15-a829efdeb4d3.png)

Can you please take a look into this as we have workshop scheduled for this lab

**Comment by himanshuahlawat31** [comment]
@shirolkar @timahenning  Can you please take a look into this

**Comment by timahenning** [comment]
Hi @himanshuahlawat31, 

Thank you for submitting this issue.  As stated on the Microsoft Cloud Workshop web site, "Allow 5 - 10 business days for review and resolution of issues."  We will try to get to this issue as soon as possible.

**Comment by himanshuahlawat31** [comment]
@timahenning @shirolkar  , we have event scheduled for this lab 

can you please check into this

**Comment by akn9050** [comment]
HI @timahenning @DawnmarieDesJardins is it possible to check on this issue today. Event is scheduled for 24th and 25th June

**Comment by shirolkar** [comment]
@akn9050 @timahenning @DawnmarieDesJardins @himanshuahlawat31 I will take a look today.

**Comment by himanshuahlawat31** [comment]
Hi @shirolkar Any update on the issue?

**Comment by shirolkar** [comment]
@himanshuahlawat31  @akn9050 @timahenning I have submitted the PR with the fix. Please note, I had to redesign the notebook and thus it was a non trivial change. Please let me know if there are any issues. Thanks. Jitendra

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #45
