### ISSUE TITLE
Databricks AML pre-req library failure

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [microsoft/MCW-Machine-Learning#9]
Hello,
I received this via email from Clement Le Roux.  Please review and advise.

As I walked through the MCW-Machine Learning workshop, I hit an issue when doing Before Hands-on-Lab activity.
https://github.com/microsoft/MCW-Machine-Learning
When trying to install Databricks AML pre-requesite library, it failed.
After different try, I finally succeeded by installing azureml-sdk[automl_databricks ], and not azureml-sdk[automl_databricks,explain].
Then I was able to successfully run notebooks with appropriate import.
When looking at Azure ML documentation, it sounds like azureml-sdk[automl_databricks ] has to be installed alone:
https://docs.microsoft.com/en-us/azure/machine-learning/service/how-to-configure-environment#azure-databricks
Warning
No other SDK extras can be installed. Choose only one of the preceding options [databricks] or [automl_databricks].
Maybe an update is needed on documentation.
Anyway, this is really great material I am going to use on the field, so thank you guys working on that 😉

Kind regards

**Comment by shirolkar** [comment]
Hi Dawnmarie: I attempted to reproduce the reported issue. I created a new Resource Group and with a new Databricks workspace. Following the exact instructions in the “Before the HOL - Machine Learning.md” guide, the library install (azureml-sdk[automl_databricks,explain]) succeeded for me. I do not see the error reported by Clement. One suggestion is to confirm that the Databricks Runtime Version used is as shown in the lab guide: 5.5 LTS ML (Scala 2.11, Spark 2.4.3). Thanks Jitendra
<img width="871" alt="cluster_configuration" src="https://user-images.githubusercontent.com/18037946/65904218-03c9e380-e38c-11e9-8e07-53ba9b0c0923.png">
<img width="870" alt="cluster_libraries" src="https://user-images.githubusercontent.com/18037946/65904230-0a585b00-e38c-11e9-9e2a-c9ed0c7329ad.png">

**Comment by timahenning** [comment]
Based on Jitendra's response, should we close this issue?

**Comment by DawnmarieDesJardins** [comment]
@timahenning
I followed up with the person who opened the issue via email 10/1.  (I can't find a GitHub ID with his name so I can't tag him here.)  I'll give him until 10/8 to respond and then assume he's been able to move forward.  Thanks!

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved.  No further contact from original author.

**Comment by magaudef** [comment]
Hi @DawnmarieDesJardins @shirolkar 

I was also walking through the same workshop, and hit the same kind of issue. 
I successfully installed the library specified in the hands-on, but, when trying to execute cell 14 in the notebook 'Model Explainability' i run into another error. I believe the error is linked to the library (explain part of the library). 

Note that we were several people running the hands on with the same conditions (the one specified in the workshop) and all had the same error.

SDK Version: 1.0.69
The scikit-learn version is 0.20.3.

Please find the error below: 

OptionalDependencyMissingException Traceback (most recent call last) <command-332673894473196> in <module>()  1 from azureml.train.automl.automlexplainer import explain_model  2  ----> 3 shap_values, expected_values, sorted_global_importance_values, sorted_global_importance_names, _ , _ = explain_model(best_model, X_train, X_test, best_run=best_run, y_train=y_train)  4   5 #Overall feature importance /databricks/python/lib/python3.6/site-packages/azureml/train/automl/automlexplainer.py in explain_model(fitted_model, X_train, X_test, best_run, features, y_train, **kwargs)  167 message = "[RunId:{}]Explain model function met import error. Error message:{}".format(run_id, import_error)  168 logger.warning(message) --> 169 raise OptionalDependencyMissingException(message).from_exception(import_error).from_exception(import_error)  170 except (ServiceException, AzureMLException) as e:  171 logging_utilities.log_traceback(e, logger, is_critical=False) /databricks/python/lib/python3.6/site-packages/azureml/train/automl/automlexplainer.py in explain_model(fitted_model, X_train, X_test, best_run, features, y_train, **kwargs)  102 run_id = ""  103 try: --> 104 from azureml.explain.model.mimic.mimic_explainer import MimicExplainer  105 from azureml.explain.model.mimic.models.lightgbm_model import LGBMExplainableModel  106 from azureml.explain.model._internal.explanation_client import ExplanationClient /databricks/python/lib/python3.6/site-packages/azureml/explain/model/__init__.py in <module>()  10 """  11  ---> 12 from .tabular_explainer import TabularExplainer  13   14 __all__ = ["TabularExplainer"] /databricks/python/lib/python3.6/site-packages/azureml/explain/model/tabular_explainer/__init__.py in <module>()  4   5 """Init file for azureml-explain-model/azureml/explain/model/tabular_explainer.""" ----> 6 from interpret.ext.blackbox import TabularExplainer  7   8 __all__ = ["TabularExplainer"] 
**OptionalDependencyMissingException: OptionalDependencyMissingException: Message: cannot import name 'TabularExplainer' InnerException cannot import name 'TabularExplainer' ErrorResponse { "error": { "code": "UserError", "inner_error": { "code": "ValidationError", "inner_error": { "code": "ScenarioNotSuported" } }, "message": "cannot import name 'TabularExplainer'" } }**

Thanks a lot for your help and for providing great hands-on like that !

Kind regards

**Comment by timahenning** [comment]
Thank you for reporting this issue.  Please take a moment to review the help and support guidance.  https://microsoftcloudworkshop.com/  We will review your issue soon.

Tim

**Comment by shirolkar** [comment]
Hi @magaudef @DawnmarieDesJardins @timahenning @ciprianjichici 

Can you confirm your 
Databricks Runtime Version: Runtime: 5.5 LTS ML (Scala 2.11, Spark 2.4.3)
as shown in the lab setup instructions **Before the HOL - Machine Learning** 

Note the correct version has **ML** in it. If I use Runtime: 5.5 LTS (Scala 2.11, Spark 2.4.3) without **ML**  then I can reproduce your issue. But when I use 5.5 LTS ML (Scala 2.11, Spark 2.4.3) it works fine. Thanks.

Jitendra

**Comment by magaudef** [comment]
Hi @shirolkar,

I confirm that I'm using the Runtime 5.5 LTS **ML** (includes Apache Spark 2.4.3, Scala 2.11) **with ML**

Thank you for your help

Mathilde

**Comment by shirolkar** [comment]
@magaudef Thanks for confirming. I am not able to reproduce this issue with Databricks Runtime Version: Runtime: 5.5 LTS ML (Scala 2.11, Spark 2.4.3). We will retest this issue again as part of the Nov content update cycle. Note that the code in cell 14 is likely to change as part of the content update as we are looking at a new way to generate explanations for AutoML models.

**Comment by DawnmarieDesJardins** [comment]
Labeling this issue as an enhancement so it can be reviewed/incorporated into the upcoming content update.

**Comment by DawnmarieDesJardins** [comment]
Closing issue with Nov 2019 content update merge

**Comment by HugoAlyona** [comment]
Hi, I trying to run the project from official documantaion and experienced the same issue. What is the solution?
https://github.com/microsoft/MLOps/tree/616368d8afbeeed7a9191ffedc56eaf5aed81b43
